language: node_js

node_js:
  - 14

cache: npm

branches:
  only:
    - main

install:
  - npm install

script:
  # - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
  # - git remote set-url https://iamyoki:${GITHUB_TOKEN}@github.com/iamyoki/example-package.git origin
  # - git symbolic-ref HEAD refs/heads/main
  # - npm run release -- --ci --no-git.requireUpstream
  - echo "hello" >> hello.md
  - git config --global user.name "Travis CI"
  - git config --global user.email "yokiyuqian@gmail.com"
  - git remote set-url origin https://iamyoki:${GITHUB_TOKEN}@github.com/iamyoki/example-package.git
  - git checkout main
  - git add .
  - git commit -m 'Update hello.md [ci skip]'
  - git push origin
# deploy:
#   provider: script
#   script: npm run release --ci
#   skip_cleanup: true
#   on:
#     branch: main
