language: node_js

node_js:
  - 14

cache: npm

branches:
  only:
    - main

install:
  - npm install

script:
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
  - git symbolic-ref HEAD refs/heads/main
  - npm run release --ci
  
# deploy:
#   provider: script
#   script: npm run release --ci
#   skip_cleanup: true
#   on:
#     branch: main
